---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - "/Applications/Launchpad.app"
    - "/Applications/Mission Control.app"
    - "/Applications/App Store.app"
    - "/Applications/Google Chrome.app"
    - "/Applications/Safari.app"
    - "/Applications/Firefox.app"
    - "/Applications/Mail.app"
    - "/Applications/Contacts.app"
    - "/Applications/Calendar.app"
    - "/Applications/IntelliJ IDEA 13.app"
    - "/Applications/IntelliJ IDEA 14 EAP.app"
    - "/Applications/VisualVM.app"
    - "/Applications/Xcode.app"
    - "/Applications/Cornerstone.app"
    - "/Applications/SourceTree.app"
    - "/Applications/Skype.app"
    - "/Applications/System Preferences.app"
    - "/Applications/VirtualBox.app"
    - "/Applications/VMware Fusion.app"
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # cli
  # shell tooling
  - role: git
    git_user_name: Dylan Schell
    git_user_email: dylan.schell@gmail.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: zsh
  - role: brew_package
    package_name: bash
  - role: brew_package
    package_name: bash-completion

  ## development
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: cask_package
    package_name: java
  - role: brew_package
    package_name: android-sdk
  - role: brew_package
    package_name: akka  
  - role: brew_package
    package_name: springboot
  - role: brew_package
    package_name: android-sdk
  - role: brew_package
    package_name: android-ndk
  - role: brew_package
    package_name: jad
  - role: brew_package
    package_name: cmake
  - role: brew_package
    package_name: liquibase
  - role: brew_package
    package_name: javarepl
  - role: brew_package
    package_name: yubikey-personalization
  - role: brew_package
    package_name: jboss-as
  - role: brew_package
    package_name: tomcat
  - role: brew_package
    package_name: tomcat-native
  - role: brew_package
    package_name: tig
  - role: brew_package
    package_name: grails
  - role: brew_package
    tap: jenv/jenv
    package_name: jenv
  - role: brew_package
    package_name: maven
  - role: brew_package
    package_name: sbt
  - role: brew_package
    package_name: groovy
  - role: brew_package
    package_name: scala
  - role: brew_package
    package_name: git-extras
  - role: brew_package
    package_name: typesafe-activator
  - role: brew_package
    package_name: vcprompt
  - role: brew_package
    package_name: giter8
  - role: brew_package
    package_name: htop-osx
  - role: brew_package
    package_name: spring-roo

  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb
  - role: brew_package
    package_name: mariadb
  ## deployment

  # desktop
  - role: cask_package
    package_name: a-better-finder-rename
  - role: cask_package
    package_name: boot2docker
  - role: cask_package
    package_name: geektool
  - role: cask_package
    package_name: handbrakebatch
  - role: cask_package
    package_name: java7
  - role: cask_package
    package_name: pgadmin3
  - role: cask_package
    package_name: sequel-pro
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: yubikey-personalization-gui
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: cakebrew
  - role: cask_package
    package_name: gfxcardstatus
  - role: cask_package
    package_name: hex-fiend
  - role: cask_package
    package_name: jd-gui
  - role: cask_package
    package_name: popcorn-time
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: visualvm
  - role: cask_package
    package_name: android-studio
  - role: cask_package
    package_name: clarify
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: iexplorer
  - role: cask_package
    package_name: macvim
  - role: cask_package
    package_name: quicksilver
  - role: cask_package
    package_name: sublime-text
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: cyberduck
  - role: cask_package
    package_name: google-drive
  - role: cask_package
    package_name: intellij-idea
  - role: cask_package
    package_name: mplayerx
  - role: cask_package
    package_name: remote-desktop-connection
  - role: cask_package
    package_name: totalterminal
  - role: cask_package
    package_name: vmware-fusion
  - role: cask_package
    package_name: aurora
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: grandperspective
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: netbeans
  - role: cask_package
    package_name: ripit
  - role: cask_package
    package_name: transmission-remote-gui
  - role: cask_package
    package_name: xquartz
  - role: cask_package
    package_name: blender
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: handbrake
  - role: cask_package
    package_name: java
  - role: cask_package
    package_name: osirix
  - role: cask_package
    package_name: screenflow
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: xscope