---
- hosts: all
  roles:
  - role: dylan
  - role: dock
    apps:
    - "/Applications/Launchpad.app"
    - "/Applications/Mission Control.app"
    - "/Applications/App Store.app"
    - "/Users/d.schell/Applications/Google Chrome.app"
    - "/Applications/Safari.app"
    - "/Users/d.schell/Applications/Firefox.app"
    - "/Applications/Mail.app"
    - "/Applications/Contacts.app"
    - "/Applications/Calendar.app"
    - "/Users/d.schell/Applications/IntelliJ IDEA 13.app"
    - "/Users/d.schell/Applications/VisualVM.app"
    - "/Applications/Xcode.app"
    - "/Applications/Cornerstone.app"
    - "/Applications/SourceTree.app"
    - "/Users/d.schell/Applications/Skype.app"
    - "/Applications/System Preferences.app"
    - "/Applications/VirtualBox.app"
    - "/Users/d.schell/Applications/VMware Fusion.app"
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # cli
  # shell tooling
  - role: git
    git_user_name: Dylan Schell
    git_user_email: dylan.schell@gmail.com
  - role: legit
  - role: hub